name = "PaperViz"
uuid = "490360e0-dce4-4d94-a8ec-e43dc4eeca08"
authors = ["Oliver Woodford"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
